# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Sampling, Data Management and Visualization
description:      'Teaching the tools to get computers to do cool science'
url:              http://atyre2.github.io/data-management
baseurl:          /data-management
email:            atyre2@unl.edu
feedbackurl:      https://docs.google.com/forms/d/e/1FAIpQLSdV_polFmoukgjcs1IC0Dd4iO1rdgwFnOds28xC_ma_z4tNIw
author:
  name:           'Drew Tyre'
  url:            https://twitter.com/atiretoo

github:
  repo:           https://github.com/atyre2/data-management
  #               Be sure the 'Issues' feature is activated in 'Settings'
